.\" Process this file with
.\" groff -man -Tascii lilyterm.1
.\"
.TH LilyTerm 1 "March 2013" "LilyTerm 0.9.9.5" "A light and eazy\-to\-use terminal emulator"
.SH NAME
LilyTerm \- A light and eazy\-to\-use terminal emulator for X.
.\" Disable justification (adjust text to left margin only)
.ad l
.SH SYNOPSIS
.HP 9
\fBlilyterm\fR
[\fB\-?\fR | \fB\-h\fR | \fB\-\-help\fR]
[\fB\-T\fR \fITITLE\fR | \fB\-\-title\fR \fITITLE\fR]
[\fB\-R\fR \fIROLE\fR | \fB\-\-role\fR \fIROLE\fR]
[\fB\-t\fR \fINUMBER\fR | \fB\-\-tab\fR \fINUMBER\fR]
[\fB\-n\fR \fITAB NAMES\fR | \fB\-\-tab_names\fR \fITAB NAMES\fR]
[\fB\-d\fR \fIDIRECTORY\fR | \fB\-\-directory\fR \fIDIRECTORY\fR]
[\fB\-g\fR \fIGEOMETRY\fR | \fB\-\-geometry\fR \fIGEOMETRY\fR]
[\fB\-l\fR | \fB\-ls\fR | \fB\-\-login\fR]
[\fB\-ut\fR]
[\fB\-H\fR | \fB\-\-hold\fR]
[\fB\-s\fR | \fB\-\-separate\fR]
[\fB\-j\fR | \fB\-\-join\fR]
[\fB\-p\fR | \fB\-\-profile\fR]
[\fB\-u\fR \fIPROFILE\fR | \fB\-\-user_profile\fR \fIPROFILE\fR]
[\fB\-v\fR | \fB\-\-version\fR]
[\fB\-e\fR \fICOMMAND\fR | \fB\-x\fR \fICOMMAND\fR | \fB\-\-execute\fR \fICOMMAND\fR]
.SH DESCRIPTION
LilyTerm is a terminal emulator for the X Window System, based on the \fBlibvte\fR library, and aims to be fast and lightweight.
.SH OPTIONS
.PP
\fB\-?\fR | \fB\-h\fR | \fB\-\-help\fR
.RS 4
Display a brief help message.
.RE
.PP
\fB\-T\fR \fITITLE\fR | \fB\-\-title\fR \fITITLE\fR
.RS 4
Specify the window title.
.RE
.PP
\fB\-R\fR \fIROLE\fR | \fB\-\-role\fR \fIROLE\fR
.RS 4
Specify the WM_WINDOW_ROLE string of window.
.RE
.PP
\fB\-t\fR \fINUMBER\fR | \fB\-\-tab\fR \fINUMBER\fR
.RS 4
Open multi tabs when starting up.
.RE
.PP
\fB\-n\fR \fITAB NAMES\fR | \fB\-\-tab_names\fR \fITAB NAMES\fR
.RS 4
Specify the tab names, separate with <Space>.
.RE
.PP
\fB\-d\fR \fIDIRECTORY\fR | \fB\-\-directory\fR \fIDIRECTORY\fR
.RS 4
Specify the init directory when starting up.
.RE
.PP
\fB\-g\fR \fIGEOMETRY\fR | \fB\-\-geometry\fR \fIGEOMETRY\fR
.RS 4
Specify the geometry of window when starting.
.br
A reasonable example value is "80x24+0+0", witch means "width x height {+\-} xoffset {+\-} yoffset" (without space).
.RE
.PP
\fB\-l\fR | \fB\-ls\fR | \fB\-\-login\fR
.RS 4
Make the shell invoked as a login shell.
.RE
.PP
\fB\-ut\fR
.RS 4
Disable recording the session in lastlog, utmp and wtmp.
.RE
.PP
\fB\-H\fR | \fB\-\-hold\fR
.RS 4
Hold the terminal window open when the command following \-e/\-x terminated.
.RE
.PP
\fB\-s\fR | \fB\-\-separate\fR
.RS 4
Run in separate process.
.RE
.PP
\fB\-j\fR | \fB\-\-join\fR
.RS 4
Integrate new created tabs to the last accessed window.
.br
It may be useful for launching multi commands with LilyTerm in a shell script.
.RE
.PP
\fB\-p\fR | \fB\-\-profile\fR
.RS 4
Got a profile sample.
.RE
.PP
\fB\-u\fR \fIPROFILE\fR | \fB\-\-user_profile\fR \fIPROFILE\fR
.RS 4
Use a specified profile.
.RE
.PP
\fB\-v\fR | \fB\-\-version\fR
.RS 4
Show the version information.
.RE
.PP
\fB\-e\fR \fICOMMAND\fR | \fB\-x\fR \fICOMMAND\fR | \fB\-\-execute\fR \fICOMMAND\fR
.RS 4
Run a command when starting up. Must be the final option.
.RE

.SH KEYBOARD CONTROL
The following key bindings may custom or disable by the right click menu \fB[Set key binding]\fR.
.PP
.PD 0
.TP 20
.BI <Ctrl><`>
Disable/Enable hyperlinks, function keys and right click menu for temporary.

.TP
.BI <Ctrl><T>
Add a New tab with current directory.

.TP
.BI <Ctrl><PgUp/PgDn>
Switch to Prev/Next tab.

.TP
.BI <Ctrl><Home/End>
Switch to First/Last tab.

.TP
.BI <Ctrl><[/]>
Move current tab Forward/Backward.

.TP
.BI <Ctrl><Up/Down>
Move current tab to First/Last.

.TP
.BI <Ctrl><F1~F12>
Switch to 1st ~ 12th tab.

.TP
.BI <Ctrl><O>
Select all the text in the Vte Terminal box.

.TP
.BI <Ctrl><+/\-/Enter>
Increase/Decrease/Reset the font size of current tab.

.TP
.BI <Alt><F11/Enter>
Switch between fullwindow/unfullwindow and fullscreen/unfullscreen state.

.TP
.BI <Shift><Left/Right>
Emulate a mouse Scroll Up/Down event on Vte Terminal box.

.TP
.BI <Shift><Up/Down>
Asks to scroll Up/Down 1 line on Vte Terminal box.

.TP
.BI <Shift><PgUp/PgDn>
Asks to scroll Up/Down on Vte Terminal box.

.TP
.BI <Ctrl><Delete/Insert>
Copy the text to clipboard / Paste the text in clipboard.

.TP
.BI <Shift><Delete/Insert>
Copy the text to primary clipboard / Paste the text in primary clipboard.
.br
i.e. Emulate a middle button mouse click to copy/paste the text.
.RE

Some key bindings that disabled by default but maybe useful:

.TP
.BI <Ctrl><Q>
Close current tab.
.br
\fIUsing \fR\fB<Ctrl><D>\fR\fI or '\fR\fBexit\fR\fI' to close tabs is recommended.\fR

.TP
.BI <Ctrl><N>
Open a new window with current directory.

.TP
.BI <Ctrl><E>
Rename the current tab.

.SH FILE
.PP
.PD 0
.TP 32
.BI /etc/xdg/lilyterm.conf
System configure file

.TP
.BI ~/.config/lilyterm/default.conf
User's profile.
.RE

Use \fB[Save settings]\fR in the right click menu to save the current tab's settings as default to the specified profile.

.SH TIPS
.PP
\fBDisplay UTF\-8 character under C locale\fR

.RS 4
Execute the following command under LilyTerm:

.RS 4
bind "set convert\-meta off"
.br
bind "set output\-meta on"
.RE

And use the right click menu to set the text encoding to "\fBUTF\-8\fR".
.RE

.PP
\fBLaunch LilyTerm under a chroot jail\fR

.RS 4
Extract \fBxauth info\fR to a file (under X):

.RS 4
xauth extract /PathToChroot/tmp/display $DISPLAY
.RE

Mount the \fBdevpts\fR device and \fB/tmp\fR (may not necessary) before chroot into a chroot jail:

.RS 4
mount /dev/pts /PathToChroot/dev/pts \-t devpts
.br
mount \-o bind /tmp /PathToChroot/tmp (may not necessary)
.RE

Merge the extracted \fBxauth info\fR and set the \fBDISPLAY\fR environ after chroot into the chroot jail:

.RS 4
xauth merge /tmp/display
.br
export DISPLAY=:0
.RE

Launch LilyTerm directly, or run it under \fBXnest\fR/\fBXephyr\fR:

.RS 4
xinit ~/.xinitrc \-\- /usr/bin/Xnest :1 \-ac \-geometry 800x600
.RE

or

.RS 4
xinit ~/.xinitrc \-\- /usr/bin/Xephyr :1 \-ac \-screen 800x600
.RE
.RE

.PP
\fB<Ctrl><S> and <Ctrl><Q> don't work under VIM:\fR

.RS 4
Use the following command to turn off '\fBflow\-Control\fR' under LilyTerm:

.RS 4
stty raw
.RE

or

.RS 4
stty \-ixon
.RE

.RE

.PP
\fBBSD Users:\fR

.RS 4
Please mount the procfs before launch LilyTerm:

.RS 4
mount \-t procfs procfs /proc
.RE

.SH ENVIRONMENT
.PP
.PD 0
.TP 15
.BI TERM
Sets what type of terminal attempts to emulate. Please always set to "\fBxterm\fR" under LilyTerm.

.TP
.BI VTE_CJK_WIDTH
Controls the width of some ideographs should be "single width (narrow)" or "double width (wide)" in a vte teminal.
.br
This environment should be set \fBbefore\fR creating a vte widget.
.br
In LilyTerm, you may set the VTE_CJK_WIDTH of a new tab to 'wide' with right click menu 'New tab with specified locale' \-> 'xx_XX.UTF\-8 (Wide)' or 'UTF\-8 (Wide)'.

.TP
.BI PROMPT_COMMAND
Customs the "Window Title" for shell.
.br
The following is a reasonable example ~/.bashrc for bash:
.RS 19
.br

case $TERM in
.br
    xterm*)
        PROMPT_COMMAND='echo \-ne "\\033]0;${HOSTNAME}: ${PWD}\\007"'
        ;;
.br
    *)
        ;;
.br
esac

.br
.RE
.RS 15
The following is a reasonable example ~/.cshrc for csh/tcsh:
.RS 4
.br

switch ($TERM)
    case "xterm*":
        setenv TITLE "%{\\033]0;%m: %~\\007%}"
        breaksw
.br
endsw

set prompt = "${TITLE}%# "

.br
.RE
.RE
.RS 15
Please visit \fIhttp://tldp.org/HOWTO/Xterm\-Title.html\fR for more details.
.RE

.SH AUTHOR
Lu, Chao\-Ming (Tetralet) <tetralet@gmail.com>

.SH SEE ALSO
xterm(1)
